CREATE TABLE INSTITUICAO(
    ID INT PRIMARY KEY,
    NOME TEXT,
    CNPJ TEXT
);

CREATE TABLE PESSOA(
    ID INT PRIMARY KEY,
    NOME TEXT,
    DATA_NASCIMENTO DATE,
    CPF TEXT
);

CREATE TABLE TURMA(
    ID INT PRIMARY KEY,
    DESCRICAO TEXT,
    ANO INT,
    SEMESTRE INT,
    NUMERO INT,
    ID_INSTITUICAO INT,
    FOREIGN KEY(ID_INSTITUICAO) REFERENCES INSTITUICAO(ID)
);

CREATE TABLE ALUNO(
    SEMESTRE_INICIO INT,
    ANO_INICIO INT,
    MATRICULA TEXT,
    ID_PESSOA INT,
    FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID)
);

CREATE TABLE PROFESSOR(
    MATRICULA TEXT,
    TITULACAO_MAXIMA INT,
    ID_PESSOA INT,
    FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(ID)
);

CREATE TABLE ALUNO_TURMA(
    ID_TURMA INT,
    ID_ALUNO INT,
    FOREIGN KEY(ID_TURMA) REFERENCES TURMA(ID),
    FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(ID_PESSOA)
);

CREATE TABLE PROFESSOR_TURMA(
    ID_TURMA INT,
    ID_PROFESSOR INT,
    FOREIGN KEY(ID_TURMA) REFERENCES TURMA(ID),
    FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSOR(ID_PESSOA)
);

CREATE TABLE MENSALIDADE(
    ID INT,
    DATA_VENCIMENTO DATE,
    VALOR NUMERIC,
    REFERENCIA TEXT,
    DATA_PAGAMENTO DATE,
    ID_INSTITUICAO INT,
    ID_ALUNO INT,
    FOREIGN KEY(ID_INSTITUICAO) REFERENCES INSTITUICAO(ID),
    FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(ID_PESSOA)
);

INSERT INTO PESSOA (
    ID,
    NOME,
    DATA_NASCIMENTO,
    CPF
) VALUES (
    1,
    'Marcos Miguel',
    '1977-08-31',
    '03188888801'
),
(
    2,
    'Melissa Miguel',
    '2000-08-31',
    '64085274101'
),
(
    3,
    'José da Silva',
    '1950-01-25',
    '12345678901'
),
(
    4,
    'Maria da Silva',
    '1960-01-01',
    '12385274196'
),
(
    5,
    'Giuliano Prado',
    '1930-01-01',
    '04185274122'
);